# -*- coding: utf-8 -*-
"""M11 PBOP 5210411229.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/194oCGEXL0YV-BbguZkj3H_Z-x48tMbb4
"""

def lsegitiga(a,t):
  luas = a*t/2
  return luas

a=int(input("Input Alas : "))
t=int(input("Input Tinggi : "))
print("Luas Segitiga yaitu : ",lsegitiga(a,t))
