# -*- coding: utf-8 -*-
"""PBO 1 gifthub.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UHJhfS6rcKT4ZDDcY0R7teaCqqwNYyZP
"""

r = int(input("masukan nilai r : " ))
phi = 3.14
luas_lingkaran = phi * r * r
print("luas lingkaran : " + str(luas_lingkaran))
