# -*- coding: utf-8 -*-
"""pbo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14byBgBz-Y8SfGl5BTCV468U048iw7Os8
"""

print("MENGHITUNG 2 BANGUN 2 DEMENSI")
print("Masukan Nilai sisi persegi")
sisi = int(input("Masukan sisi Persegi"))
l1 = sisi * sisi
print("Masukan Nilai Alas segitiga")
alas = int(input("Masukan Alas Segitiga"))
print("Masukan Nilai Tinggi Segitiga")
tinggi = int(input("Masukan Tinggi Segitiga"))
l2 = float(1) / 2 * alas * tinggi
ltot = l1 + l2
print("Hasil dari bangun tersebut")
print(ltot)
